baseURL: "https://drklrd.github.io/"
languageCode: "en-us"
title: "codeScape"
theme: "PaperMod"
paginate: 5

params:
  # home-info mode
  ShowShareButtons: true
  homeInfoParams:
    Title: "Namaste (à¤¨à¤®à¤¸à¥à¤¤à¥‡!) ðŸ™"
    Content: >
      Warm welcome to my blogging place! I am Saurav. I love maps and building software tools/products with maps. Currently, I am helping build *[Baato](https://baato.io)*, a maps based APIs service for Nepal.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/srvbhattarai"
    - name: github
      url: "https://github.com/drklrd"
    - name: openstreetmap
      url: "https://www.openstreetmap.org/user/srvbhattarai"
